name: build-deploy

on:
  push:
    branches:
      - master

jobs:
  build-test:
    name: Testing the project
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Build virtualenv
        run: |
          pip install virtualenv
          virtualenv -p python venv
          pip install -r requirements
          pip install pytest
          pip install -e .
      - name: Launch pytest
        run: |
          pytest

  deploy-webserver:
    name: Deploying on webserver
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Calling webhook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.DOCKER_WEBHOOK_URL }}
