name: build-deploy

on:
  push:
    branches:
      - master

jobs:
  build-test:
    name: Testing the project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Build virtualenv
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv -p python venv
          pip install -r requirements.txt
          pip install pytest
          pip install -e .
      - name: Prepare temporary configuration file
        run: |
          cp conf.yml.sample conf.yml
          cp sshportal.db.sample sshportal.db
      - name: Launch pytest
        run: |
          pytest

  deploy-webserver:
    name: Deploying on webserver
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Calling webhook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.DOCKER_WEBHOOK_URL }}
